version: 2.1

jobs:
  deploy_lambda:
    docker: 
      - image: cimg/node:14.11.0
    environment:
      AWS_PROVIDER: aws

    working_directory: ~/Snowflake-healthcheck

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies

      - run:
          name: Install Dependencies
          command: |
            npm install -g aws-cli
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies

      - run:
          name: Build react app
          command: |
            cd snowflake_healthcheck
            npm run build

      - run:
          name: Deploy React App to Existing S3 Bucket
          command: |
            aws s3 sync build/ s3://react-test-healthcheck --acl public-read

workflows:
  build_and_deploy:
    jobs:
      - deploy_lambda
          # filters:
          #   branches:
          #     only: master
