version: 2.1
  
jobs:
  deploy_react:
    docker: 
      - image: cimg/node:14.11.0
    environment:
      AWS_PROVIDER: aws

    working_directory: ~/Snowflake-healthcheck/snowflake_healthcheck

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies

      - run:
          name: Install Dependencies
          command: |
            npm install
            sudo apt-get update && sudo apt-get install python3.7
            sudo curl -O https://bootstrap.pypa.io.get-pip.py && sudo python get-pip.py
            sudo pip install awscli --upgrade

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies

      - run:
          name: Build react app
          command: |
            npm run build

      - run:
          name: Deploy React App to Existing S3 Bucket
          command: |
            aws s3 sync build/ s3://react-test-healthcheck --acl public-read --delete

workflows:
  build_and_deploy:
    jobs:
      - deploy_react
          # filters:
          #   branches:
          #     only: master
