version: 2.1

jobs:
  deploy_react:
    docker: 
      - image: cimg/node:14.11.0
    environment:
      AWS_PROVIDER: aws

    working_directory: ~/Snowflake-healthcheck

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            npm install
            sudo apt-get install python-pip python-dev
            sudo pip install awscli --upgrade

      - run:
          name: Build react app
          command: |
            npm run build

      - run:
          name: Deploy React App to Existing S3 Bucket
          command: |
            aws s3 sync build/ s3://react-test-healthcheck --acl public-read --delete

workflows:
  build_and_deploy:
    jobs:
      - deploy_react
          # filters:
          #   branches:
          #     only: master
