version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0
  
jobs:
  deploy_react:
    docker: 
      - image: cimg/node:14.11.0
    environment:
      AWS_PROVIDER: aws

    working_directory: ~/Snowflake-healthcheck/snowflake_healthcheck

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies

      - run:
          name: Install Dependencies
          command: |
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies

      - run:
          name: Build react app
          command: |
            npm run build

      - run:
          name: Deploy React App to Existing S3 Bucket
          command: |
            aws s3 sync build/ s3://react-test-healthcheck --acl public-read

workflows:
  build_and_deploy:
    jobs:
      - install-aws-cli
      - deploy_react
          requires:
            - install-aws-cli

          # filters:
          #   branches:
          #     only: master
