version: 2.1

jobs:
  deploy_lambda:
    docker: 
      - image: cimg/node:14.11.0
    environment:
      AWS_PROVIDER: aws

    working_directory: ~/Snowflake-healthcheck

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.12

      - restore_cache:
          keys:
          - v1-dependencies

      - run:
          name: Install Dependencies
          command: |
            sudo npm i -g serverless
            npm install
            pushd healthcheck/layers && chmod +x get_layer_packages.sh && ./get_layer_packages.sh && popd
            cd healthcheck && sls package
            sls deploy --package .serverless

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies

      # - run:
      #     name: Update and Make Dependency Layer 
      #     command: |
      #       pushd healthcheck/layers && chmod +x get_layer_packages.sh && ./get_layer_packages.sh && popd
            
      # - run:
      #     name: Deploy Lambda Function and Layers to AWS Console
      #     command: |
      #       cd healthcheck && sls package
      #       sls deploy --package .serverless

workflows:
  build_and_deploy:
    jobs:
      - deploy_lambda
          # filters:
          #   branches:
          #     only: master
